
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVISION = 73;
  public static final int ENTEROO = 18;
  public static final int PARENTESIS_ABRE = 52;
  public static final int PTCOMA = 2;
  public static final int CONTINUAR = 33;
  public static final int TIPOS_ORDENAMIENTO = 43;
  public static final int PARENTESIS_CIERRA = 53;
  public static final int POTENCIA = 75;
  public static final int MENSAJE = 46;
  public static final int SI = 28;
  public static final int KEEP = 26;
  public static final int PISTA = 15;
  public static final int CORCHETE_ABRE = 50;
  public static final int LONGITUD = 45;
  public static final int FALSE = 25;
  public static final int NOT = 69;
  public static final int NOR = 67;
  public static final int ORDENAR = 42;
  public static final int MENORQUE = 60;
  public static final int VAR = 27;
  public static final int DECIMALL = 20;
  public static final int SALIR = 32;
  public static final int HACER = 37;
  public static final int INDENT_C = 10;
  public static final int PARA = 35;
  public static final int INDENT_A = 9;
  public static final int INCREMENTO = 3;
  public static final int COMA = 49;
  public static final int LLAVE_CIERRA = 55;
  public static final int ENTERO = 17;
  public static final int MODULO = 74;
  public static final int TRUE = 24;
  public static final int CHARR = 8;
  public static final int IGUAL = 56;
  public static final int NOTT = 12;
  public static final int DECIMAL = 19;
  public static final int CHAR = 22;
  public static final int BOOLEAN = 21;
  public static final int NOMBRE = 14;
  public static final int SWITCH = 30;
  public static final int IMPRIMIR = 13;
  public static final int DECREMENTO = 4;
  public static final int NOTAS_MUSICALES = 40;
  public static final int LLAVE_ABRE = 54;
  public static final int ARREGLO = 48;
  public static final int EOF = 0;
  public static final int MIENTRAS = 36;
  public static final int DEFAULT = 34;
  public static final int SUMA = 70;
  public static final int SUMARIZAR = 44;
  public static final int MENORIGUAL = 62;
  public static final int DIFERENCIACION = 58;
  public static final int PRINCIPAL = 47;
  public static final int OR = 66;
  public static final int error = 1;
  public static final int REPRODUCIR = 39;
  public static final int RESTA = 71;
  public static final int MAYORQUE = 59;
  public static final int IGUALACION = 57;
  public static final int SINO = 29;
  public static final int SUMA_SIMPLIFICADA = 5;
  public static final int ESNULO = 63;
  public static final int EXTIENDE = 16;
  public static final int UMENOS = 11;
  public static final int CASO = 31;
  public static final int MULTIPLICACION = 72;
  public static final int ESPERAR = 41;
  public static final int RETORNA = 38;
  public static final int CADENAA = 7;
  public static final int CADENA = 23;
  public static final int MAYORIGUAL = 61;
  public static final int AND = 64;
  public static final int CORCHETE_CIERRA = 51;
  public static final int PROGRAMA = 6;
  public static final int NAND = 65;
  public static final int XOR = 68;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "INCREMENTO",
  "DECREMENTO",
  "SUMA_SIMPLIFICADA",
  "PROGRAMA",
  "CADENAA",
  "CHARR",
  "INDENT_A",
  "INDENT_C",
  "UMENOS",
  "NOTT",
  "IMPRIMIR",
  "NOMBRE",
  "PISTA",
  "EXTIENDE",
  "ENTERO",
  "ENTEROO",
  "DECIMAL",
  "DECIMALL",
  "BOOLEAN",
  "CHAR",
  "CADENA",
  "TRUE",
  "FALSE",
  "KEEP",
  "VAR",
  "SI",
  "SINO",
  "SWITCH",
  "CASO",
  "SALIR",
  "CONTINUAR",
  "DEFAULT",
  "PARA",
  "MIENTRAS",
  "HACER",
  "RETORNA",
  "REPRODUCIR",
  "NOTAS_MUSICALES",
  "ESPERAR",
  "ORDENAR",
  "TIPOS_ORDENAMIENTO",
  "SUMARIZAR",
  "LONGITUD",
  "MENSAJE",
  "PRINCIPAL",
  "ARREGLO",
  "COMA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "IGUAL",
  "IGUALACION",
  "DIFERENCIACION",
  "MAYORQUE",
  "MENORQUE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "ESNULO",
  "AND",
  "NAND",
  "OR",
  "NOR",
  "XOR",
  "NOT",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "POTENCIA"
  };
}

